### ISSUE TITLE
Issues using with Java

### ISSUE THREAD

**Issue by drusellers** [negativetwelve/heroku-buildpack-subdir#4]
On the off chance you have a quick fix, I'm trying to use with JAVA build pack but can't for the life of me find the java executable.

```
depot-ui=https://github.com/heroku/heroku-buildpack-nodejs.git
depot-service=https://github.com/heroku/heroku-buildpack-java.git
```

Its finding the node/webpack stuff that I'm using just fine
Its finding the maven stuff just fine during compile

But, then in the time to run the application I can't find JAVA to save my life.
I also don't see the $JAVA_OPTS

Is there something that I need to do to get the `java` exe working?

![image](https://user-images.githubusercontent.com/63355/31677769-75d88996-b331-11e7-97ce-7caa1f400e8b.png)

Is it the lack of java here?

**Comment by drusellers** [comment]
Yes, yes it was. :)

**Comment by Photonios** [comment]
I think this issue can be closed @negativetwelve
