### ISSUE TITLE
Buildpack cleanup removes project's vendor folders

### ISSUE THREAD

**Issue by JGefroh** [negativetwelve/heroku-buildpack-subdir#8]
The changes made in PR #6 also removes folders named `vendor` that belong to the project being built. This breaks multi-stage builds where those source files may be required for postprocessing by following stages, such as a JS build -> Ruby Processing -> Rails Asset Pipeline build.

The workaround for the time being is to specify the commit to use in the buildpack URL via `https://github.com/negativetwelve/heroku-buildpack-subdir#176688a0ea7dc4aa3510e7a1613846fb7d1f59fe`.

**Comment by negativetwelve** [comment]
Thanks for bringing this up, I'm going to revert that commit for now and revisit a better solution. cc @Photonios

**Comment by negativetwelve** [comment]
It has been reverted #9.

@Photonios let's revisit the solution you proposed and discuss what might work better. We shouldn't assume specific folders because this buildpack should work with many types of applications.

**Comment by Photonios** [comment]
My apologies for introducing a breaking change, I've proposed a better solution here:

https://github.com/negativetwelve/heroku-buildpack-subdir/issues/10
